# pip install pupil-apriltags
"""
april_test.py -- Live AprilTag detection with 6DOF pose via laptop webcam.

Library  : pupil-apriltags  (AprilTag 3 Python bindings)
Family   : tag36h11
Calib    : camera_calibration.yaml  (generated by charuco_calibrate.py)

TAG_SIZE : physical side length of your printed tag in metres.
           Change this to match your actual tag before running.

Run:
    python3 april_test.py
Keys:
    q   quit
"""

import collections
import time

import cv2
import numpy as np
import pupil_apriltags as apriltag
import yaml

# ── Physical tag size -- CHANGE THIS to match your printed tag ────────────────
TAG_SIZE = 0.05   # metres (5 cm side length)

CALIB_FILE  = "camera_calibration.yaml"

FONT        = cv2.FONT_HERSHEY_SIMPLEX
FILL_CLR    = (0, 170, 255)
BORDER_CLR  = (0, 220, 60)
CORNER_CLRS = [
    (0,   60, 255),   # 0 bottom-left  -- red
    (255, 80,   0),   # 1 bottom-right -- blue
    (0,  220,  60),   # 2 top-right    -- green
    (255,200,   0),   # 3 top-left     -- cyan
]
CENTER_CLR  = (255, 255, 255)
ID_CLR      = (255, 230, 0)
FPS_CLR     = (255, 200, 0)
BLACK       = (0, 0, 0)
FILL_ALPHA  = 0.30
FPS_BUF_LEN = 30


def _load_calibration(path):
    with open(path) as f:
        d = yaml.safe_load(f)
    K = np.array(d["camera_matrix"]["data"],
                 dtype=np.float64).reshape(3, 3)
    D = np.array(d["distortion_coefficients"]["data"],
                 dtype=np.float64)
    return K, D


def _put_outlined(img, text, xy, color, scale=0.65, thickness=2):
    cv2.putText(img, text, xy, FONT, scale, BLACK, thickness + 2, cv2.LINE_AA)
    cv2.putText(img, text, xy, FONT, scale, color, thickness,     cv2.LINE_AA)


def _draw_tag(vis, tag, K, D):
    pts = tag.corners.astype(np.int32)  # (4, 2)

    # Semi-transparent fill
    overlay = vis.copy()
    cv2.fillPoly(overlay, [pts], FILL_CLR)
    cv2.addWeighted(overlay, FILL_ALPHA, vis, 1.0 - FILL_ALPHA, 0, vis)

    # Border
    cv2.polylines(vis, [pts], isClosed=True,
                  color=BORDER_CLR, thickness=2, lineType=cv2.LINE_AA)

    # Colour-coded corner dots
    for idx, pt in enumerate(pts):
        c = tuple(pt)
        cv2.circle(vis, c, 7, BLACK, -1)
        cv2.circle(vis, c, 6, CORNER_CLRS[idx], -1)

    # Centre dot
    cx, cy = int(tag.center[0]), int(tag.center[1])
    cv2.circle(vis, (cx, cy), 5, BLACK, -1)
    cv2.circle(vis, (cx, cy), 4, CENTER_CLR, -1)

    # 3D pose axes + distance label
    if tag.pose_R is not None and tag.pose_t is not None:
        rvec, _ = cv2.Rodrigues(tag.pose_R)
        tvec    = tag.pose_t

        # Draw X (red), Y (green), Z (blue) axes -- length = half tag size
        cv2.drawFrameAxes(vis, K, D, rvec, tvec, TAG_SIZE * 0.5)

        dist_m = float(np.linalg.norm(tvec))
        dist_label = f"{dist_m * 100:.1f} cm"
        tw, _ = cv2.getTextSize(dist_label, FONT, 0.6, 2)[0]
        _put_outlined(vis, dist_label, (cx - tw // 2, cy + 22),
                      (200, 200, 255), scale=0.6, thickness=2)

    # ID label
    label = f"ID:{tag.tag_id}"
    tw, _ = cv2.getTextSize(label, FONT, 0.8, 2)[0]
    _put_outlined(vis, label, (cx - tw // 2, cy - 18), ID_CLR, scale=0.8, thickness=2)


def main():
    K, D = _load_calibration(CALIB_FILE)
    fx, fy = K[0, 0], K[1, 1]
    cx, cy = K[0, 2], K[1, 2]
    print(f"Calibration loaded: fx={fx:.1f} fy={fy:.1f} cx={cx:.1f} cy={cy:.1f}")

    detector = apriltag.Detector(
        families="tag36h11",
        nthreads=1,
        quad_decimate=1.0,
        quad_sigma=0.0,
        refine_edges=1,
        decode_sharpening=0.25,
    )

    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        raise RuntimeError("Cannot open camera 0")

    fps_buf = collections.deque(maxlen=FPS_BUF_LEN)
    t_last  = time.perf_counter()
    print(f"AprilTag live detector (tag36h11, tag_size={TAG_SIZE*100:.0f} cm) -- press 'q' to quit")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Frame grab failed -- exiting.")
            break

        t_now = time.perf_counter()
        fps_buf.append(1.0 / max(t_now - t_last, 1e-9))
        t_last = t_now
        fps = sum(fps_buf) / len(fps_buf)

        gray       = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        detections = detector.detect(
            gray,
            estimate_tag_pose=True,
            camera_params=[fx, fy, cx, cy],
            tag_size=TAG_SIZE,
        )

        vis = frame.copy()
        for tag in detections:
            _draw_tag(vis, tag, K, D)

        h, w = vis.shape[:2]
        _put_outlined(vis, f"Tags: {len(detections)}", (10, 28),      FPS_CLR, scale=0.7)
        _put_outlined(vis, f"{fps:.1f} FPS",           (w - 110, 28), FPS_CLR, scale=0.7)
        _put_outlined(vis, f"tag36h11  tag_size={TAG_SIZE*100:.0f} cm  [q] quit",
                      (10, h - 12), (180, 180, 180), scale=0.5, thickness=1)

        cv2.imshow("AprilTag Detector -- tag36h11", vis)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()
    print("Done.")


if __name__ == "__main__":
    main()
