"""
aruco_test.py -- Live ArUco marker detection with 6DOF pose via laptop webcam.

Dictionary : DICT_4X4_50  (matches the CharUco calibration sheet)
API        : cv2.aruco.ArucoDetector  (OpenCV 4.7+)
Calib      : camera_calibration.yaml  (generated by charuco_calibrate.py)

TAG_SIZE : physical side length of your printed marker in metres.

Run:
    python3 aruco_test.py
Keys:
    q   quit
"""

import collections
import time

import cv2
import numpy as np
import yaml

TAG_SIZE   = 0.05   # metres (5 cm side length)
CALIB_FILE = "camera_calibration.yaml"

FONT        = cv2.FONT_HERSHEY_SIMPLEX
BORDER_CLR  = (0, 220, 80)
ID_CLR      = (0, 200, 255)
CORNER0_CLR = (0, 60, 255)
FPS_CLR     = (255, 200, 0)
BLACK       = (0, 0, 0)
FPS_BUF_LEN = 30


def _load_calibration(path):
    with open(path) as f:
        d = yaml.safe_load(f)
    K = np.array(d["camera_matrix"]["data"],
                 dtype=np.float64).reshape(3, 3)
    D = np.array(d["distortion_coefficients"]["data"],
                 dtype=np.float64)
    return K, D


def _put_outlined(img, text, xy, color, scale=0.65, thickness=2):
    cv2.putText(img, text, xy, FONT, scale, BLACK, thickness + 2, cv2.LINE_AA)
    cv2.putText(img, text, xy, FONT, scale, color, thickness,     cv2.LINE_AA)


def main():
    K, D = _load_calibration(CALIB_FILE)
    print(f"Calibration loaded: fx={K[0,0]:.1f} fy={K[1,1]:.1f} "
          f"cx={K[0,2]:.1f} cy={K[1,2]:.1f}")

    aruco_dict   = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    aruco_params = cv2.aruco.DetectorParameters()
    detector     = cv2.aruco.ArucoDetector(aruco_dict, aruco_params)

    # 3D object points of a single marker (tag frame, origin at centre)
    half = TAG_SIZE / 2.0
    obj_pts = np.array([
        [-half,  half, 0],
        [ half,  half, 0],
        [ half, -half, 0],
        [-half, -half, 0],
    ], dtype=np.float64)

    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        raise RuntimeError("Cannot open camera 0")

    fps_buf = collections.deque(maxlen=FPS_BUF_LEN)
    t_last  = time.perf_counter()
    print(f"ArUco live detector (DICT_4X4_50, tag_size={TAG_SIZE*100:.0f} cm) -- press 'q' to quit")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Frame grab failed -- exiting.")
            break

        t_now = time.perf_counter()
        fps_buf.append(1.0 / max(t_now - t_last, 1e-9))
        t_last = t_now
        fps = sum(fps_buf) / len(fps_buf)

        corners, ids, _ = detector.detectMarkers(frame)
        vis = frame.copy()

        if ids is not None and len(ids) > 0:
            cv2.aruco.drawDetectedMarkers(vis, corners, ids, borderColor=BORDER_CLR)

            for i, corner_set in enumerate(corners):
                pts = corner_set[0]  # (4, 2) float32

                # Red dot on corner 0 for orientation
                c0 = (int(pts[0, 0]), int(pts[0, 1]))
                cv2.circle(vis, c0, 7, (0, 60, 255), -1)
                cv2.circle(vis, c0, 7, BLACK, 1)

                # Solve pose
                img_pts = pts.reshape(4, 1, 2).astype(np.float64)
                ok, rvec, tvec = cv2.solvePnP(
                    obj_pts, img_pts, K, D, flags=cv2.SOLVEPNP_IPPE_SQUARE)

                cx_i = int(pts[:, 0].mean())
                cy_i = int(pts[:, 1].mean())

                if ok:
                    cv2.drawFrameAxes(vis, K, D, rvec, tvec, TAG_SIZE * 0.5)
                    dist_m = float(np.linalg.norm(tvec))
                    dist_label = f"{dist_m * 100:.1f} cm"
                    tw, _ = cv2.getTextSize(dist_label, FONT, 0.6, 2)[0]
                    _put_outlined(vis, dist_label,
                                  (cx_i - tw // 2, cy_i + 22),
                                  (200, 200, 255), scale=0.6, thickness=2)

                _put_outlined(vis, f"ID:{int(ids[i][0])}",
                              (cx_i - 28, cy_i - 18),
                              ID_CLR, scale=0.75, thickness=2)

        h, w = vis.shape[:2]
        n = 0 if ids is None else len(ids)
        _put_outlined(vis, f"Markers: {n}",    (10, 28),      FPS_CLR, scale=0.7)
        _put_outlined(vis, f"{fps:.1f} FPS",   (w - 110, 28), FPS_CLR, scale=0.7)
        _put_outlined(vis, f"DICT_4X4_50  tag_size={TAG_SIZE*100:.0f} cm  [q] quit",
                      (10, h - 12), (180, 180, 180), scale=0.5, thickness=1)

        cv2.imshow("ArUco Detector -- DICT_4X4_50", vis)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()
    print("Done.")


if __name__ == "__main__":
    main()
